-- Seed data matching approved design reference

insert into institutes (name, code, slug, city, description, is_constituent, established_year, programmes, principal_name, principal_email, vice_principal_name, vice_principal_email, student_affairs_office, sort_order) values
('Chandka Medical College', 'CMC', 'chandka-medical-college', 'Larkana',
  'One of Sindh''s oldest medical colleges, training physicians for upper Sindh for five decades. Home to the MBBS programme, a 1,650-bed teaching hospital network, and 28 clinical departments.',
  true, 1973,
  '[{"level":"UG","name":"Bachelor of Medicine, Bachelor of Surgery (MBBS)","duration":"5 YRS"},{"level":"PG","name":"MS / MD Clinical Specialties (14 disciplines)","duration":"4-5 YRS"},{"level":"PG","name":"M.Phil Basic Medical Sciences","duration":"2 YRS"},{"level":"PG","name":"MSc Public Health","duration":"2 YRS"},{"level":"DIP","name":"Postgraduate Diplomas (Anaesthesia, Radiology, Gynae)","duration":"1 YR"}]'::jsonb,
  'Prof. Dr. Abdul Rasheed Shaikh', 'principal.cmc@smbbmu.edu.pk',
  'Prof. Dr. Shabnam Naz', 'vp.academics.cmc@smbbmu.edu.pk',
  'Block B, Ground Floor · Mon-Fri 9:00-15:00', 1),
('Ghulam Muhammad Mahar Medical College', 'GMMMC', 'ghulam-muhammad-mahar-medical-college', 'Sukkur',
  'Constituent medical college serving the Sukkur region with an MBBS programme and affiliated teaching hospital.',
  true, 2010,
  '[{"level":"UG","name":"Bachelor of Medicine, Bachelor of Surgery (MBBS)","duration":"5 YRS"}]'::jsonb,
  'Prof. Dr. Ghulam Sarwar Mahar', 'principal.gmmmc@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 2),
('Bibi Aseefa Dental College', 'BADC', 'bibi-aseefa-dental-college', 'Larkana',
  'Constituent dental college offering the BDS programme with a full range of dental clinical departments.',
  true, 2011,
  '[{"level":"UG","name":"Bachelor of Dental Surgery (BDS)","duration":"4 YRS"}]'::jsonb,
  'Prof. Dr. Nasreen Rind', 'principal.badc@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 3),
('Benazir College of Nursing', 'BCON', 'benazir-college-of-nursing', 'Larkana',
  'Constituent nursing college offering generic and post-RN nursing programmes.',
  true, 2013,
  '[{"level":"UG","name":"BSN (Generic)","duration":"4 YRS"},{"level":"UG","name":"BSN (Post-RN)","duration":"2 YRS"}]'::jsonb,
  'Prof. Rehana Soomro', 'principal.bcon@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 4),
('Institute of Pharmacy', 'IOP', 'institute-of-pharmacy', 'Larkana',
  'Constituent institute offering the Pharm-D programme and pharmaceutical sciences research.',
  true, 2014,
  '[{"level":"UG","name":"Doctor of Pharmacy (Pharm-D)","duration":"5 YRS"}]'::jsonb,
  'Prof. Dr. Imran Memon', 'director.iop@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 5),
('Institute of Physiotherapy & Rehabilitation Sciences', 'IPRS', 'institute-of-physiotherapy-rehabilitation-sciences', 'Larkana',
  'Constituent institute offering the Doctor of Physical Therapy programme.',
  true, 2015,
  '[{"level":"UG","name":"Doctor of Physical Therapy (DPT)","duration":"5 YRS"}]'::jsonb,
  'Prof. Dr. Saima Baloch', 'director.iprs@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 6),
('College of Medical Technology', 'CMT', 'college-of-medical-technology', 'Larkana',
  'Constituent college offering allied health technology diplomas and degrees.',
  true, 2016,
  '[{"level":"UG","name":"BS Medical Laboratory Technology","duration":"4 YRS"},{"level":"UG","name":"BS Radiology Technology","duration":"4 YRS"}]'::jsonb,
  'Prof. Dr. Aijaz Bhutto', 'principal.cmt@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 7),
('Sukkur College of Nursing & Midwifery', 'SCNM', 'sukkur-college-of-nursing-midwifery', 'Sukkur',
  'Constituent nursing and midwifery college serving the Sukkur region.',
  true, 2017,
  '[{"level":"UG","name":"BSN (Generic)","duration":"4 YRS"},{"level":"DIP","name":"Diploma in Midwifery","duration":"3 YRS"}]'::jsonb,
  'Prof. Rukhsana Abro', 'principal.scnm@smbbmu.edu.pk', null, null,
  'Student Affairs Office · Mon-Fri 9:00-15:00', 8);

-- CMC and GMMMC maintain their own websites; nav links for them go external.
-- The remaining institutes use their internal /institutes/[slug] profiles.
update institutes set website_url = 'https://cmc.edu.pk/' where code = 'CMC';
update institutes set website_url = 'https://www.gmc-suk.edu.pk/' where code = 'GMMMC';

insert into faculty (name, designation, department, institute_id, sort_order) values
('Prof. Dr. Shabnam Naz', 'Professor & Chairperson', 'Anatomy', (select id from institutes where code = 'CMC'), 1),
('Prof. Dr. Aftab A. Soomro', 'Professor', 'Medicine', (select id from institutes where code = 'CMC'), 2),
('Dr. Farzana Memon', 'Associate Professor', 'Physiology', (select id from institutes where code = 'CMC'), 3),
('Dr. Imran A. Sheikh', 'Associate Professor', 'Surgery', (select id from institutes where code = 'CMC'), 4),
('Dr. Sanam Bhutto', 'Assistant Professor', 'Pathology', (select id from institutes where code = 'CMC'), 5),
('Dr. Zulfiqar Laghari', 'Assistant Professor', 'Medicine', (select id from institutes where code = 'CMC'), 6),
('Dr. Rubina Chandio', 'Senior Lecturer', 'Anatomy', (select id from institutes where code = 'CMC'), 7),
('Dr. Waseem Abbasi', 'Lecturer', 'Physiology', (select id from institutes where code = 'CMC'), 8);

insert into announcements (title, slug, category, ref_number, body, excerpt, kicker, published_at, attachments) values
('Examination Certificate Fees Challan', 'examination-certificate-fees-challan', 'examination', 'SMBBMU/EXAM/2026/430',
  'Candidates requiring examination certificates must deposit the prescribed fee using the attached challan form before submitting their application to the Controller of Examinations office.',
  'Candidates requiring examination certificates must deposit the prescribed fee using the attached challan form.', null,
  '2026-07-01T09:00:00Z',
  '[{"name":"Examination Certificate Fees Challan.pdf","url":"#","size_kb":286}]'::jsonb),
('Tender Notice: Supply of Laboratory Equipment & Consumables 2026-27', 'tender-notice-laboratory-equipment-consumables-2026-27', 'tender', 'SMBBMU/PROC/2026/091',
  'Sealed tenders are invited from registered suppliers for the supply of laboratory equipment and consumables for the academic year 2026-27. Tender documents may be obtained from the Procurement Office during working hours.',
  'Sealed tenders are invited from registered suppliers for the supply of laboratory equipment and consumables for 2026-27.', null,
  '2026-06-30T09:00:00Z',
  '[{"name":"Tender Document - Lab Equipment 2026-27.pdf","url":"#","size_kb":940}]'::jsonb),
('Notification: Revised Academic Calendar 2026-27', 'notification-revised-academic-calendar-2026-27', 'circular', 'SMBBMU/REG/2026/212',
  'The competent authority has approved a revised academic calendar for the session 2026-27. All constituent institutes are directed to align their teaching schedules accordingly.',
  'The competent authority has approved a revised academic calendar for the session 2026-27.', null,
  '2026-06-28T09:00:00Z',
  '[{"name":"Revised Academic Calendar 2026-27.pdf","url":"#","size_kb":512}]'::jsonb),
('Result of Postgraduate Entry Test for Session July 2026', 'result-postgraduate-entry-test-session-july-2026', 'admission', 'SMBBMU/ADM/2026/188',
  'The result of the Postgraduate Entry Test conducted for admission to Session July 2026 has been declared. Candidates may check their roll number in the attached gazette.',
  'The result of the Postgraduate Entry Test conducted for admission to Session July 2026 has been declared.', null,
  '2026-06-24T09:00:00Z',
  '[{"name":"PG Entry Test Result Gazette - July 2026.pdf","url":"#","size_kb":1340}]'::jsonb),
('Result of BSN (Generic) Year-II, Semester-III Regular Examination, Session 2023-24', 'result-bsn-generic-year-ii-semester-iii-regular-examination-2023-24', 'examination', 'SMBBMU/EXAM/2026/417',
  'The result of BSN (Generic) Year-II, Semester-III Regular Examination, Session 2023-24, conducted by the university has been declared and is attached.',
  'The result of BSN (Generic) Year-II, Semester-III Regular Examination, Session 2023-24 has been declared.', null,
  '2026-06-23T09:00:00Z',
  '[{"name":"BSN Generic Year-II Sem-III Result.pdf","url":"#","size_kb":780}]'::jsonb),
('Rescheduling of Interviews for Various Positions in Colleges, Institutes & Departments', 'rescheduling-interviews-various-positions-colleges-institutes-departments', 'job', 'SMBBMU/HR/2026/096',
  'Interviews for various teaching and non-teaching positions across constituent colleges, institutes and departments have been rescheduled. Candidates should note the revised dates in the attached notice.',
  'Interviews for various positions across constituent colleges, institutes and departments have been rescheduled.', null,
  '2026-06-22T09:00:00Z',
  '[{"name":"Revised Interview Schedule.pdf","url":"#","size_kb":410}]'::jsonb),
('Revised Time Table: 3rd Professional MBBS (Supplementary) OSPE Examination, Session 2022-23', 'revised-time-table-3rd-professional-mbbs-supplementary-ospe-examination-2022-23', 'examination', 'SMBBMU/EXAM/2026/417',
  'The OSPE examination of 3rd Professional MBBS (Supplementary), Session 2022-23, has been rescheduled. Candidates are directed to note the revised dates and report to their examination centres thirty minutes before commencement. Admit cards remain valid for the revised dates. For queries, contact the Controller of Examinations office during working hours. No separate intimation will be issued to individual candidates.',
  'The OSPE examination has been rescheduled. Candidates are directed to note the revised dates and report to their centres thirty minutes before commencement. Admit cards remain valid.', null,
  '2026-06-18T09:00:00Z',
  '[{"name":"Revised OSPE Time Table - 3rd Prof MBBS (Supplementary).pdf","url":"#","size_kb":412},{"name":"Examination Centre Allocation List.pdf","url":"#","size_kb":1229}]'::jsonb),
('Time Table for Supplementary Examination — 1st, 2nd & 3rd Year MBBS', 'time-table-supplementary-examination-1st-2nd-3rd-year-mbbs', 'examination', 'SMBBMU/EXAM/2026/409',
  'The time table for the Supplementary Examination of 1st, 2nd and 3rd Year MBBS is attached. Candidates should verify their examination centre and roll number.',
  'The time table for the Supplementary Examination of 1st, 2nd and 3rd Year MBBS is attached.', null,
  '2026-06-17T09:00:00Z',
  '[{"name":"Supplementary Time Table - 1st 2nd 3rd Year MBBS.pdf","url":"#","size_kb":365}]'::jsonb),
('Time Table for the Supplementary Examination of 1st Year MBBS (Term-Back)', 'time-table-supplementary-examination-1st-year-mbbs-term-back', 'examination', 'SMBBMU/EXAM/2026/408',
  'The time table for the Supplementary Examination of 1st Year MBBS (Term-Back) candidates is attached.',
  'The time table for the Supplementary Examination of 1st Year MBBS (Term-Back) candidates is attached.', null,
  '2026-06-17T09:00:00Z',
  '[{"name":"Supplementary Time Table - 1st Year MBBS Term-Back.pdf","url":"#","size_kb":298}]'::jsonb),
('Rescheduling of Interviews for Admission to Postgraduate Courses, Session July 2026', 'rescheduling-interviews-admission-postgraduate-courses-july-2026', 'admission', 'SMBBMU/ADM/2026/175',
  'Interviews for admission to postgraduate courses for Session July 2026 have been rescheduled. The revised schedule is attached.',
  'Interviews for admission to postgraduate courses for Session July 2026 have been rescheduled.', null,
  '2026-06-17T09:00:00Z',
  '[{"name":"Revised PG Admission Interview Schedule.pdf","url":"#","size_kb":355}]'::jsonb),
('Postgraduate Entry Test for Session July 2026', 'postgraduate-entry-test-session-july-2026', 'admission', 'SMBBMU/ADM/2026/160',
  'Applications are invited for the Postgraduate Entry Test for Session July 2026. Eligible candidates should apply before the closing date mentioned in the attached notice.',
  'Applications are invited for the Postgraduate Entry Test for Session July 2026.', null,
  '2026-06-15T09:00:00Z',
  '[{"name":"PG Entry Test Notice - July 2026.pdf","url":"#","size_kb":420}]'::jsonb),
('Result of Final Professional MBBS (Supplementary) Examination, Session 2020-21', 'result-final-professional-mbbs-supplementary-examination-2020-21', 'examination', 'SMBBMU/EXAM/2026/399',
  'The result of the Final Professional MBBS (Supplementary) Examination, Session 2020-21, has been declared and is attached.',
  'The result of the Final Professional MBBS (Supplementary) Examination, Session 2020-21, has been declared.', null,
  '2026-06-11T09:00:00Z',
  '[{"name":"Final Prof MBBS Supplementary Result 2020-21.pdf","url":"#","size_kb":690}]'::jsonb),
('Flag hoisting & plantation drive mark Youm-e-Azadi', 'flag-hoisting-plantation-drive-mark-youm-e-azadi', 'news', null,
  'The university marked Youm-e-Azadi with a flag hoisting ceremony and a plantation drive across the Larkana campus, attended by faculty, staff and students.',
  'The university marked Youm-e-Azadi with a flag hoisting ceremony and a plantation drive across the Larkana campus.', 'CAMPUS',
  '2026-07-10T09:00:00Z', '[]'::jsonb),
('Free mega medical camp brings care to Warah', 'free-mega-medical-camp-brings-care-to-warah', 'event', null,
  'SMBBMU faculty and students held a free mega medical camp in Warah, providing consultation, diagnostics and medicines to residents of the surrounding area.',
  'SMBBMU faculty and students held a free mega medical camp in Warah, providing consultation, diagnostics and medicines.', 'OUTREACH',
  '2026-07-08T09:00:00Z', '[]'::jsonb),
('NAHE faculty trainings: photos & highlights', 'nahe-faculty-trainings-photos-highlights', 'event', null,
  'The National Academy of Higher Education (NAHE) conducted a series of faculty development trainings at SMBBMU, covering modern pedagogy and assessment methods.',
  'NAHE conducted a series of faculty development trainings at SMBBMU covering modern pedagogy and assessment.', 'FACULTY',
  '2026-06-10T09:00:00Z', '[]'::jsonb),
('SMBBMU ranked among top 1500+ universities worldwide', 'smbbmu-ranked-top-1500-universities-worldwide', 'news', null,
  'SMBBMU has been ranked among the top 1500+ universities worldwide in an international ranking, reflecting the university''s growing academic and research standing.',
  'SMBBMU has been ranked among the top 1500+ universities worldwide in an international ranking.', 'CAMPUS',
  '2026-06-28T09:00:00Z', '[]'::jsonb),
('The 7th Convocation comes to Larkana this December.', '7th-convocation-comes-to-larkana-this-december', 'event', null,
  'Graduates of MBBS, BDS, Nursing and allied health programmes will be conferred degrees on 18 December. Registration closes 30 November. The ceremony will be held at the university''s main campus in Larkana, with the Chief Guest to be announced closer to the date.',
  'Graduates of MBBS, BDS, Nursing and allied health programmes will be conferred degrees on 18 December. Registration closes 30 November.', 'CONVOCATION',
  '2026-07-11T09:00:00Z', '[]'::jsonb);

insert into pages (slug, title, standfirst, body, meta) values
('vc-message', 'Vice Chancellor''s Message', null,
  'I envision the university transformed into a place of academic excellence which produces critical thinkers, competent health professionals and community leaders.',
  '{"name":"Prof. Dr. Nusrat Shah","title":"Vice Chancellor, SMBBMU Larkana"}'::jsonb),
('quality-enhancement-cell', 'Quality Enhancement Cell',
  'The QEC safeguards academic standards across all constituent institutes through systematic self-assessment, programme review and compliance with HEC quality assurance frameworks.',
  E'## Mandate\n\nEstablished under HEC directives, the Cell reports directly to the Vice Chancellor and coordinates with the Quality Assurance Agency. Its remit covers curriculum review, faculty appraisal, and institutional performance evaluation conducted on an annual cycle.\n\n## Core functions\n\n- Annual self-assessment reports for every degree programme\n- Programme team reviews and rubric-based scoring\n- Graduate and employer survey administration\n- Liaison with HEC QAA and accreditation councils (PMDC, PNC, PCP)\n\n## Assessment cycle 2026-27\n\n| Phase | Window | Responsible |\n|---|---|---|\n| Self-assessment reports | SEP - NOV | Programme teams |\n| External review visits | JAN - MAR | QEC + external assessors |\n| Implementation plans | APR - JUN | Deans & heads of department |',
  '{"related_links":[{"label":"HEC Quality Assurance Framework","url":"#"},{"label":"Programme review rubrics","url":"#"},{"label":"Institutional Performance Evaluation","url":"#"}],"contact":{"email":"qec@smbbmu.edu.pk","phone":"+92 74 9410 703 · EXT 188","location":"Admin Block, Main Campus, Larkana"}}'::jsonb),
('directorate-of-medical-education', 'Directorate of Medical Education',
  'The DME leads curriculum development, faculty training and assessment reform across all constituent colleges and institutes.',
  E'## Mandate\n\nThe Directorate of Medical Education (DME) coordinates curriculum design, faculty development, and modern assessment practice across all constituent colleges under HEC and PMDC guidance.\n\n## Core functions\n\n- Curriculum review and integration across professional years\n- Faculty development workshops in medical education\n- OSCE/OSPE assessment design and item banking\n- Student support and remediation programme oversight\n\n## Training calendar 2026-27\n\n| Workshop | Window | Audience |\n|---|---|---|\n| Curriculum integration workshop | AUG - SEP | Module coordinators |\n| Assessment & item-writing bootcamp | OCT - NOV | Examination staff |\n| Simulation-based teaching primer | FEB - MAR | Clinical faculty |',
  '{"related_links":[{"label":"PMDC Curriculum Guidelines","url":"#"}],"contact":{"email":"dme@smbbmu.edu.pk","phone":"+92 74 9410 703 · EXT 192","location":"Academic Block, Main Campus, Larkana"}}'::jsonb),
('administration', 'Administration',
  'The university''s administrative structure supports academic governance across all constituent institutes.',
  E'## Registrar''s Office\n\nThe Registrar''s Office is responsible for admissions, examinations records, and academic governance across the university.\n\n## Directorates\n\n- Directorate of Admissions\n- Directorate of Finance\n- Directorate of Medical Education\n- Directorate of Human Resources',
  '{}'::jsonb),
('scholarship-financial-aid-policy', 'Scholarship & Financial Aid Policy',
  'Guidelines governing need-based and merit-based financial assistance for enrolled students.',
  E'## Eligibility\n\nStudents enrolled in any constituent institute with demonstrated financial need or outstanding academic merit may apply for financial assistance each semester.\n\n## How to apply\n\nApplications are submitted through the Directorate of Finance along with supporting documentation. Awards are reviewed on a rolling basis.',
  '{"related_links":[{"label":"Directorate of Finance","url":"/contact"}]}'::jsonb),
('the-university', 'The University',
  'SMBBMU, Larkana was established to expand access to quality medical, dental, nursing and allied health education across upper Sindh.',
  E'## About SMBBMU\n\nShaheed Mohtarma Benazir Bhutto Medical University, Larkana is a public sector university comprising eight constituent institutes across Larkana and Sukkur, offering undergraduate and postgraduate programmes in medicine, dentistry, nursing, pharmacy, physiotherapy and allied health sciences.\n\n## Vision\n\nTo be a leading centre of medical education, research and community health service in Sindh and beyond.',
  '{}'::jsonb);

insert into downloads (title, file_url, category, file_size_kb, page_slug) values
('QEC Annual Report 2025-26', '#', 'Reports', 2458, 'quality-enhancement-cell'),
('Self-Assessment Manual', '#', 'Guidelines', 860, 'quality-enhancement-cell'),
('Fee Structure 2026-27', '#', 'Admissions', 512, null),
('Prospectus 2026-27', '#', 'Admissions', 4200, null),
('Academic Calendar 2026-27', '#', 'Academics', 380, null),
('Undergraduate Curriculum Framework', '#', 'Academics', 1650, null),
('Scholarship & Financial Aid Policy', '#', 'Policies', 290, null),
('Anti-Harassment Policy', '#', 'Policies', 210, null);
